CREATE DATABASE Lanchonete
USE Lanchonete

CREATE TABLE Cargo(
	ID INT NOT NULL IDENTITY(1,1),
	Nome VARCHAR(50) NOT NULL,
	Salario DECIMAL(7,2) NOT NULL CHECK(Salario > 0),
	Descricao VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE Funcionario(
	ID INT NOT NULL IDENTITY(1,1),
	Nome VARCHAR(100) NOT NULL,
	Telefone VARCHAR(11) CHECK(LEN(Telefone) >= 10),
	Email VARCHAR(200) NOT NULL,
	DataContrato DATE NOT NULL DEFAULT(GETDATE()),
	ID_Cargo INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_Cargo) REFERENCES Cargo(ID)
)

CREATE TABLE Cliente(
	ID INT NOT NULL IDENTITY(1, 1),
	Nome VARCHAR(100) NOT NULL,
	Telefone VARCHAR(11) NOT NULL CHECK(LEN(Telefone) >=10), 
	CPF CHAR(11) NOT NULL CHECK(LEN(CPF) = 11),
	Logradouro VARCHAR(200) NOT NULL,
	Numero INT NOT NULL CHECK(Numero >= 0),
	CEP CHAR(8) NOT NULL CHECK(LEN(CEP) = 8),
	Complemento VARCHAR(255),
	PRIMARY KEY(ID)
)

CREATE TABLE Pedido(
	Num_Pedido INT NOT NULL IDENTITY(1,1),
	ValorTotal DECIMAL(7,2) NOT NULL CHECK(ValorTotal > 0),
	DataPedido DATE NOT NULL DEFAULT(GETDATE()),
	StatusPedido VARCHAR(20) NOT NULL DEFAULT('Em Preparo'),
	ID_Cliente INT NOT NULL,
	PRIMARY KEY(Num_Pedido),
	FOREIGN KEY(ID_Cliente) REFERENCES Cliente(ID)
)

CREATE TABLE Categoria(
	ID INT NOT NULL IDENTITY(1,1),
	Nome VARCHAR(50) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE Produto(
	ID INT NOT NULL IDENTITY(1,1),
	Nome VARCHAR(50) NOT NULL,
	QtdEstoque INT NOT NULL CHECK(QtdEstoque >= 0),
	ValorUnit DECIMAL(7,2) NOT NULL CHECK(ValorUnit > 0),
	ID_Categoria INT NOT NULL,
	ID_Fornecedor INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_Categoria) REFERENCES Categoria(ID),
	FOREIGN KEY(ID_Fornecedor) REFERENCES Fornecedor(ID)
)

CREATE TABLE Fornecedor(
	ID INT NOT NULL IDENTITY(1, 1),
	Nome VARCHAR(100) NOT NULL,
	Telefone VARCHAR(11) NOT NULL CHECK(LEN(Telefone) >=10),
	CNPJ CHAR(14) NOT NULL CHECK(LEN(CNPJ) = 14),
	Logradouro VARCHAR(200) NOT NULL,
	Numero INT NOT NULL CHECK(Numero >= 0),
	CEP CHAR(8) NOT NULL CHECK(LEN(CEP) = 8),
	Complemento VARCHAR(255),
	PRIMARY KEY(ID)
)

CREATE TABLE Item_Pedido(
	Num_Pedido INT NOT NULL,
	ID_Produto INT NOT NULL,
	Qtd INT NOT NULL,
	ValorUnit DECIMAL(7,2) NOT NULL,
	ValorTotalItem DECIMAL(7,2) NOT NULL
	PRIMARY KEY(Num_Pedido, ID_Produto),
	FOREIGN KEY(Num_Pedido) REFERENCES Pedido(Num_Pedido),
	FOREIGN KEY(ID_Produto) REFERENCES Produto(ID)
)